Repository vexide/vexide, pull requests merged in 2024-04, with the labels that each got.

#11 refactor: implement panic handler with vex-sdk
  packages/vexide-devices/src/screen.rs
  packages/vexide-panic/Cargo.toml
  packages/vexide-panic/src/lib.rs
Labels: enhancement

#28 fix(controllers): allow using connected controllers
  packages/vexide-devices/src/controller.rs
Labels: bug

#36 fix: get main macro working with only vexide as a dependency
  packages/vexide-macro/Cargo.toml
  packages/vexide-macro/src/lib.rs
  packages/vexide-startup/Cargo.toml
  packages/vexide-startup/src/lib.rs
  packages/vexide/Cargo.toml
  packages/vexide/src/lib.rs
Labels: bug

#38 fix(screen): flush before advancing lines
  packages/vexide-devices/src/screen.rs
Labels: bug

#42 fix: competition API while disconnected
  packages/vexide-core/src/competition.rs
Labels: core

#49 refactor: redo program linkerscript
  armv7a-vexos-eabi.json
  packages/vexide-startup/link/cold-sections.ld
  packages/vexide-startup/link/cold.ld
  packages/vexide-startup/link/memory.ld
  packages/vexide-startup/link/prelude.ld
  packages/vexide-startup/link/v5.ld
  packages/vexide-startup/src/lib.rs
Labels: enhancement, startup
